name: hedge_manager
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  window_manager: ^0.2.1

  #webview 版本
  webview_flutter: ^3.0.2 #android & ios
  path_provider: ^2.0.9
  desktop_webview_window: ^0.1.6
  #  webview_windows: ^0.1.8

  dio: ^4.0.6
  shared_preferences: ^2.0.13
  json_serializable: ^6.2.0
  build_runner: ^2.1.10
  bot_toast: ^4.0.1
  url_launcher: ^6.1.2
  shell: ^2.0.0
  device_info_plus: ^3.2.3
  flutter_swiper_plus: ^2.0.4
  sentry_flutter: ^6.5.1
  tray_manager: ^0.1.7 #系统托盘

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/


  fonts:
    - family: AliIcons
      fonts:
        - asset: assets/icons/iconfont.ttf

